{% set version = "19.3.6.5" %}
{% set sha256 = "224cbdcf1e182424f4261be82568a95360035f85665db30da8f53bddbae63f6e" %}

package:
  name: erlang
  version: {{ version }}

source:
  fn: otp_src_{{ version }}.tar.gz
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf 2.*
    - m4 1.4.*
    - perl 5.22.2.1
    - readline 7.0
    - openssl 1.0.*
    - ncurses 5.9
    - zlib 1.2.11
    - toolchain
  run:
    - readline 7.0
    - openssl 1.0.*
    - ncurses 5.9
    - zlib 1.2.11

test:
  commands:
    - erl -version

about:
  home: http://www.erlang.org/
  license: Apache 2.0
  summary: "A programming language used to build massively scalable soft real-time systems with requirements on high availability."

extra:
  recipe-maintainers:
    - scopatz
    - jakirkham
    - sodre
