{% set version = "21.0" %}
{% set sha256 = "5a2d8e33c39a78a2dcc0c39bf9d2dfdf2974f0fad28385b4ede020a2321d643f" %}

package:
  name: erlang
  version: {{ version }}

source:
  fn: otp_src_{{ version }}.tar.gz
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf 2.*
    - m4 1.4.*
    - perl 5.20.3.1
    - readline 7.0
    - openssl 1.0.*
    - ncurses 5.9
    - zlib 1.2.11
    - toolchain
  run:
    - readline 7.0
    - openssl 1.0.*
    - ncurses 5.9
    - zlib 1.2.11

test:
  commands:
    - erl -version
    - erlc

about:
  home: http://www.erlang.org/
  license: Apache 2.0
  summary: "A programming language used to build massively scalable soft real-time systems with requirements on high availability."

extra:
  recipe-maintainers:
    - scopatz
    - jakirkham
    - sodre
