{% set version = "22.1" %}

package:
  name: erlang
  version: {{ version }}

source:
  fn: otp_src_{{ version }}.tar.gz
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: 7b26f64eb6c712968d8477759fc716d64701d41f6325e8a4d0dd9c31de77284a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf 2.*
    - m4 1.4.*
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - erl -version
    - erlc

about:
  home: http://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: "A programming language used to build massively scalable soft real-time systems with requirements on high availability."

extra:
  recipe-maintainers:
    - scopatz
    - jakirkham
    - sodre
