{% set version = "18.3" %}

package:
  name: erlang
  version: {{ version }}

source:
  fn: otp_src_{{ version }}.tar.gz
  url: http://erlang.org/download/otp_src_{{ version }}.tar.gz
  sha256: "fdab8129a1cb935db09f1832e3a7d511a4aeb2b9bb3602ca6a7ccb9730d5c9c3"
  patches:
    # Adds a patch to pickup `perl` from the path instead of
    # forcing it to come from `/usr/bin`. See PR for details.
    #
    # https://github.com/erlang/otp/pull/1097
    #
    - PR_1097.diff

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
    - m4
    - perl
    - readline 6.2*
    - openssl 1.0.*
    - ncurses 5.9*
    - zlib 1.2.*
    - libatomic_ops
  run:
    - readline 6.2*
    - openssl 1.0.*
    - ncurses 5.9*
    - zlib 1.2.*
    - libatomic_ops

test:
  commands:
    - erl -version

about:
  home: http://www.erlang.org/
  license: Apache 2.0
  summary: "A programming language used to build massively scalable soft real-time systems with requirements on high availability."

extra:
  recipe-maintainers:
    - scopatz
    - jakirkham
