travis:
  secure:
    BINSTAR_TOKEN: W524Nd/NW7TI2Ruob9R/a1EoCfGJhLUof395cOSHgLn1wtr6hQ0kn7zzaWRdjkoahUWPLJpCGIw6frFdKvWP1++vYU1HLMQqNDPFTPJ7nED1KItlrSTgir54O/Xb/+eXFxtBThZ1rv4GoX8WFYNkFbfnQJK+oBNPd9l6qOQlrvoFgjc9E74oBmUW1fbZkzYgym48S0oMfyjhXygig4W8c2D5UPD62EGEceTfqoa3hMYKRtSlulWCXRi6Jfovo1J5sBH3GQO5fiR7YKOMIpaAEHOCgWPstkNwHwwHQaSPQ4gqs3MnOPZ90WjizfkNJlQJbbOTgWLr+CywGDJy2oiSGOm/+uWnJqVPiBehrAcz8QkvfMfdBWEaAzGLQZ7ua/U8RepaWAFcAEnMKXYQKSfr8r/RskIFFyRTfbhGlAJKXO0l9kqFKsWtNA0C4NIZrh8i/jtsBen1s/KcfRb3yjRwNCPs0fpgmiNwcpph4lf07ttDbfKWSqK+Quzvqmilk/KELiAejbwT6lvJl2gtYwrvaTLx55TsSqORxY3el/sQ9raKYPRLSUuG9T8KKaXNfn8lifz3H7yyLNhZdJtU/hr90oGE9tYNJDwbIUme9o/hL77+kkkZ8hYDaJjw17qYqHQsKc8noG+TcGZUTS/nZ+wus4uPs2va9sHD034VHSAgX4w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
