travis:
  secure:
    BINSTAR_TOKEN: eTgBf4aKW+aeFzXXGr026mdxUMJUTvYGQnzFn20D86DN6Q7pE+UCVJJEY41+9U4pu9+edukMTs6NDIQSD7lNB4DId96WbuyfJVe05NKlMe2kNMmJHCvDsqKmPozplluP1qyAE95EGAT+sjQcn/ut0So+I2Ef1X5MWVSrQNjh03ZZQ3/6GwiEi4RPJCnL41NhkOs9rBwSEQNoOx0bkt8qc89K1sAacfV9o3ezZXC43i/SlmU7h577qaGMgbTcAs6dedT+Vq/m12PRJflBQBnCXX1zGOygPSfrGOYL8rGLlpTPGZB/yFIxkPr3kB1gVSmI5wSC5fIix5Gtf80Ut0kU3SpdqdFO0C9sDvwn3k3ifgFpJ1x55ZIR0N+XxAPYJWPZUfppR2GbMm15neMNT5ka19av8wXglF6rkBnJyJGW+Tp8Ul2gcq1/j8sJB8dwgPoJadZR+QFA5B7UlmHKgxtMDTubEa0QUFFrlsffLVyak8qNvqRjgqaWQ1SqlALGPyyJh8r3ZxhYF0G+s7Scryxg+yN+VaTBGByDiBZP4BFQuq0+u+cmCI57JArrZw/y/CvEzZDrJ5BTuihvPMD+y1L+nZOGvQVDTgF1MKgNIRdcWvLeO6PCBdWX3x0tcooLBYJsxpRDf0VBwJVL2UxwegYW5U5INFf/cz6LojUXB0kiGQc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
