travis:
  secure:
    BINSTAR_TOKEN: Exh7c9NxbZOIwijQ32pOZTL561zOronswXmV7nwtmviiLUQZEix9EqSH0juiG7uxKHCRweMM4+CipZ2YC2TYS7MEeO/LrpbrLXvT4MJ8HAY/REzvPTRoql6y9+ZyaJlCfghKxJ0snNLz/5hEfR8c7YuNFALIa67COBExACZ7PpS5rYNUMDuzC7e5XwYHh9+gwtr9LslLkzn0f6JxencbvscbRVkANbG3xn14PXP7IP4qdhpHsvsasWwqMLbNPDk9nHe6Yzs9wFIQwgwKswTyF1wB/G/ZgehsdM4E5UajnwkssKb3AZy/0mcnvp9EziMVrrxJJ21bu5RG8xfG1Yck1PDbU3Q+InQCHITC7geO/j8xQdYABX2LAjp2uSVmK7R+2Tz+puUCzBULHzV4Yo6g99A5JUQeMgbdcTdGddTx4Qt1VKqbBNi/wWO/zFwQHIuIapWLNgNVxeSD9xxPxjNXi3qPzTQyIiQbgkwoMi2+jjRdrs3snaWcoF9CEPPla3W6SpQzH8ll1qCwA3PZsp7mF7H2f69iIfxhCdJ/E9hzh4m3xPO6SBPTH52kFUN8V+3vp6wUWXtMMBLl/qM1zcqnQGkieHvQdf1Sr06/ekfyMEnbUw+23X9sYlIvt9UTZBHIzKlUMJ2uxsUNy24t/tWjXloBbxhuOH3aX+gegXwjbTE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
